Disabled /sys root-only access in order to make applications like lxpanel's batt plugin to work. Moved cgroup mount back to /sys/fs/cgroup.
Now adding /mnt/boot and /mnt/live to /etc/fstab during initramfs
stage to enable fsck checks (works for vfat/ext2 /mnt/boot).
Filesystem checks are executed in automatic repair mode during
startup and shutdown.

Disabled GRSecurity's time change logging (initramfd and sysctl.conf), 
so that splash silent mode VT is not garbled.

Fixed VT switch from splash silent mode when starting/not starting
X server. Also disabled text cursor on the VT used by X.

diff --git a/src/root/setup b/src/root/setup
--- a/src/root/setup
+++ b/src/root/setup
@@ -292,13 +292,14 @@ for mfam in `eselect mesa list | sed -n 's/^\([^[:blank:]]\+\).*/\1/p'`; do
 done
 
 
-sinfo "Updating PCI and USB lists"
+# The piciids/usbids sites are notorious for various failures
+sinfo "Updating PCI and USB lists (ignoring errors)"
 
 sed -i '/^PCI_COMPRESSED_IDS=1$/d; s/^\(DEST=.*\)\.gz$/\1/' /usr/sbin/update-pciids
-update-pciids -q
+update-pciids -q || true
 
 rm -f /usr/share/misc/usb.ids.gz
-update-usbids -q
+update-usbids -q || true
 
 if [ ! -e /usr/share/misc/pci.ids  -o  ! -e /usr/share/misc/usb.ids ]; then
     sinfo "Do PCI/USB IDs lists use compressed format exclusively?"
