Fixed initial persistence setup and certificates generation for baselayout-2.
Made Tor hidden service key and certificates generation more
robust (poweroff-proof).

Converted otfe-resize to Bourne shell.

diff --git a/src/root/setup b/src/root/setup
--- a/src/root/setup
+++ b/src/root/setup
@@ -294,13 +294,13 @@ done
 
 
 # The piciids/usbids sites are notorious for various failures
-sinfo "Updating PCI and USB lists (ignoring errors)"
+sinfo "Updating PCI and USB lists"
 
 sed -i '/^PCI_COMPRESSED_IDS=1$/d; s/^\(DEST=.*\)\.gz$/\1/' /usr/sbin/update-pciids
-update-pciids -q || true
+update-pciids -q || echo "update-pciids failed (ignoring)"
 
 rm -f /usr/share/misc/usb.ids.gz
-update-usbids -q || true
+update-usbids -q || echo "update-usbids failed (ignoring)"
 
 if [ ! -e /usr/share/misc/pci.ids  -o  ! -e /usr/share/misc/usb.ids ]; then
     sinfo "Do PCI/USB IDs lists use compressed format exclusively?"
diff --git a/src/usr/local/libexec/suexec/gen-anon-hostname b/src/usr/local/libexec/suexec/gen-anon-hostname
--- a/src/usr/local/libexec/suexec/gen-anon-hostname
+++ b/src/usr/local/libexec/suexec/gen-anon-hostname
@@ -10,27 +10,36 @@
 tordir=${SECURITY_HOME}/tor/hidden_service
 base32=hex2base32
 
-
-# Intentionally fail if dir already exists
-mkdir ${tordir}
+tordirtmp=${tordir}.tmp
 
 
-# Key generation can be lengthy, set some traps
-trap 'if [ $? != 0 ]; then rm -r ${tordir}; fi' 0
-trap : INT QUIT TERM SEGV
+# Fail if dir already exists
+if [ -e ${tordir} ]; then
+    echo ${tordir} already exists
+    exit 1
+fi
+
+
+# Create temporary directory (erase previous one, if exists)
+rm -rf ${tordirtmp}
+mkdir  ${tordirtmp}
 
 
 # Generate RSA-1024 with exponent 65537, as per spec
 # Use genrsa instead of genpkey, for result similarity
-openssl genrsa -f4 -out ${tordir}/private_key 1024 2>/dev/null
+openssl genrsa -f4 -out ${tordirtmp}/private_key 1024 2>/dev/null
 
 
 # Tor hashes ASN.1 RSAPublicKey instead of SubjectPublicKeyInfo,
 # which contains RSAPublicKey at offset 22; it then converts the
 # first half of SHA-1 hash to Base32
-hex=`openssl pkey -in ${tordir}/private_key -pubout -outform der 2>/dev/null \
+hex=`openssl pkey -in ${tordirtmp}/private_key -pubout -outform der 2>/dev/null \
          | tail -c +23 | sha1sum | head -c 20`
 [ ${#hex} = 20 ]
 b32=`${base32} ${hex}`
 
-echo ${b32}.onion > ${tordir}/hostname
+echo ${b32}.onion > ${tordirtmp}/hostname
+
+
+# Commit new directory
+mv -T ${tordirtmp} ${tordir}
diff --git a/src/usr/local/libexec/suexec/gen-anon-username b/src/usr/local/libexec/suexec/gen-anon-username
--- a/src/usr/local/libexec/suexec/gen-anon-username
+++ b/src/usr/local/libexec/suexec/gen-anon-username
@@ -9,9 +9,12 @@
 
 base32=hex2base32
 
-sslconf=${XDG_CONFIG_HOME}/ssl/extensions.cnf
+sslconf=/mnt/live${XDG_CONFIG_HOME}/ssl/extensions.cnf
 certdir=${SECURITY_HOME}/ssl/certs
 keysdir=${SECURITY_HOME}/ssl/private
+
+certdirtmp=${certdir}.tmp
+keysdirtmp=${keysdir}.tmp
 
 # reqsubj not affected by LC_ALL
 rsabits=8192
@@ -20,60 +23,70 @@ reqsubj='/O=Liberté Linux/CN=Anonymous'
 crtdays=18300
 
 
-# Intentionally fail if CA dir already exists
-mkdir ${certdir} ${keysdir}
+# Fail if CA dir already exists
+if [ -e ${certdir}  -a  -e ${keysdir} ]; then
+    echo ${certdir} and ${keysdir} already exist
+    exit 1
+fi
 
 
-# Key generation can be lengthy, set some traps
-trap 'if [ $? != 0 ]; then rm -r ${certdir} ${keysdir}; fi' 0
-trap : INT QUIT TERM SEGV
+# Create temporary directories (erase previous ones, if exist)
+rm -rf ${certdirtmp} ${keysdirtmp} ${certdir} ${keysdir}
+mkdir  ${certdirtmp} ${keysdirtmp}
 
 
 # Generate RSA key + X.509 self-signed root CA certificate
 openssl req -batch -new -utf8 -subj "${reqsubj}" \
-            -newkey rsa:${rsabits} -nodes -keyout ${keysdir}/root.pem    \
-            -x509 -days ${crtdays} -sha${shabits} -out ${certdir}/ca.pem \
+            -newkey rsa:${rsabits} -nodes -keyout ${keysdirtmp}/root.pem    \
+            -x509 -days ${crtdays} -sha${shabits} -out ${certdirtmp}/ca.pem \
             -config ${sslconf} -extensions root
 
 
 # Save 32-character Base32 username (root CA SHA-1 hash)
-fingerprint=`openssl x509 -in ${certdir}/ca.pem -outform der | sha1sum | head -c 40`
+fingerprint=`openssl x509 -in ${certdirtmp}/ca.pem -outform der | sha1sum | head -c 40`
 [ ${#fingerprint} = 40 ]
-${base32} ${fingerprint} > ${certdir}/username
+${base32} ${fingerprint} > ${certdirtmp}/username
 
 
 # In absence of lifetime/backup policy and in presence of padding,
 # it's fine to use the same key for encryption and authentication
-ln -s root.pem ${keysdir}/sign.pem
-ln -s root.pem ${keysdir}/decrypt.pem
+ln -s root.pem ${keysdirtmp}/sign.pem
+ln -s root.pem ${keysdirtmp}/decrypt.pem
 
 
 # Generate X.509 verification certificate
 openssl req -batch -new -utf8 -subj "${reqsubj}" \
-            -key ${keysdir}/sign.pem |           \
-openssl x509 -req -days ${crtdays} -sha${shabits} -out ${certdir}/verify.pem  \
-             -CA ${certdir}/ca.pem -CAkey ${keysdir}/root.pem -CAcreateserial \
+            -key ${keysdirtmp}/sign.pem |        \
+openssl x509 -req -days ${crtdays} -sha${shabits} -out ${certdirtmp}/verify.pem \
+             -CA ${certdirtmp}/ca.pem -CAkey ${keysdirtmp}/root.pem             \
+             -CAcreateserial -CAserial ${certdirtmp}/certs.srl                  \
              -extfile ${sslconf} -extensions verify 2>/dev/null
 
 
 # Generate X.509 encryption certificate
 openssl req -batch -new -utf8 -subj "${reqsubj}" \
-            -key ${keysdir}/decrypt.pem |        \
-openssl x509 -req -days ${crtdays} -sha${shabits} -out ${certdir}/encrypt.pem \
-             -CA ${certdir}/ca.pem -CAkey ${keysdir}/root.pem                 \
+            -key ${keysdirtmp}/decrypt.pem |     \
+openssl x509 -req -days ${crtdays} -sha${shabits} -out ${certdirtmp}/encrypt.pem \
+             -CA ${certdirtmp}/ca.pem -CAkey ${keysdirtmp}/root.pem              \
+             -CAserial ${certdirtmp}/certs.srl                                   \
              -extfile ${sslconf} -extensions encrypt 2>/dev/null
 
 
 # Sanity checks
 checks=`
 openssl verify -x509_strict -check_ss_sig -policy_check -purpose crlsign      \
-              -CAfile ${certdir}/ca.pem -CApath /dev/null ${certdir}/ca.pem
+              -CAfile ${certdirtmp}/ca.pem -CApath /dev/null ${certdirtmp}/ca.pem
 openssl verify -x509_strict -check_ss_sig -policy_check -purpose smimesign    \
-              -CAfile ${certdir}/ca.pem -CApath /dev/null ${certdir}/verify.pem
+              -CAfile ${certdirtmp}/ca.pem -CApath /dev/null ${certdirtmp}/verify.pem
 openssl verify -x509_strict -check_ss_sig -policy_check -purpose smimeencrypt \
-              -CAfile ${certdir}/ca.pem -CApath /dev/null ${certdir}/encrypt.pem
+              -CAfile ${certdirtmp}/ca.pem -CApath /dev/null ${certdirtmp}/encrypt.pem
 `
 
-test "${checks}" = "${certdir}/ca.pem: OK
-${certdir}/verify.pem: OK
-${certdir}/encrypt.pem: OK"
+test "${checks}" = "${certdirtmp}/ca.pem: OK
+${certdirtmp}/verify.pem: OK
+${certdirtmp}/encrypt.pem: OK"
+
+
+# Commit new directories
+mv -T ${certdirtmp} ${certdir}
+mv -T ${keysdirtmp} ${keysdir}
