Fresh build-related improvements.

diff --git a/src/root/setup b/src/root/setup
--- a/src/root/setup
+++ b/src/root/setup
@@ -99,7 +99,7 @@ if [ "$1" = fresh  -o  ! -d /usr/src/linux-${kversion} ]; then
 
     sinfo "Applying kernel patches"
     spatch /usr/local/portage/distfiles/fbcondecor-0.9.6-2.6.38.patch        -d /usr/src/linux -p1
-    spatch /usr/local/portage/distfiles/unionfs-2.5.9.1_for_2.6.38.4.diff.gz -d /usr/src/linux -p1
+    spatch /usr/local/portage/distfiles/unionfs-2.5.9.2_for_2.6.38.8.diff.gz -d /usr/src/linux -p1
 
 
     # Filter locales before remerging libc
@@ -305,13 +305,15 @@ done
 
 
 # The piciids/usbids sites are notorious for various failures
-sinfo "Updating PCI and USB lists"
+sinfo "Updating PCI, USB, and SMART databases"
 
 sed -i '/^PCI_COMPRESSED_IDS=1$/d; s/^\(DEST=.*\)\.gz$/\1/' /usr/sbin/update-pciids
-update-pciids -q || echo "update-pciids failed (ignoring)"
+update-pciids -q     || echo "update-pciids failed (ignoring)"
 
 rm -f /usr/share/misc/usb.ids.gz
-update-usbids -q || echo "update-usbids failed (ignoring)"
+update-usbids -q     || echo "update-usbids failed (ignoring)"
+
+update-smart-drivedb || echo "update-smart-drivedb failed (ignoring)"
 
 if [ ! -e /usr/share/misc/pci.ids  -o  ! -e /usr/share/misc/usb.ids ]; then
     sinfo "Do PCI/USB IDs lists use compressed format exclusively?"
