Split complex code sections in "src" build phase into helper scripts
The helper scripts can be executed independently, and cover:
  - kernel(s) compilation
  - initramfs generation
  - customize-locale menus generation
  - I2P netDb generation
  - Syslinux directory generation
  - listing missing firmwares
  - PCI IDs, USB IDs, SMART drives and I2P hosts databases verification

I2P netDb generation script now skips update if netDb was generated
less than 24h ago. In addition, routerInfos are fetched faster due
to enabled compression.

diff --git a/src/home/anon/bin/customize-locale b/src/home/anon/bin/customize-locale
--- a/src/home/anon/bin/customize-locale
+++ b/src/home/anon/bin/customize-locale
@@ -4,6 +4,12 @@ cldir=/usr/local/share/customize-locale
 locdef=${XDG_CONFIG_HOME}/shell/locale
 
 
+if [ ! -e ${locdef} ]  &&  ! touch ${locdef} 2>/dev/null; then
+    echo "Could not create ${locdef}"
+    exit 1
+fi
+
+
 update_var() {
     local var="$1" value="$2"
 
@@ -65,6 +71,6 @@ if [ -n "${newtz}" ]; then
 fi
 
 if [ -n "${newkbd}" ]; then
-    update_var X11_KBD_LAYOUT  "`echo "${newkbd}" | cut -d. -f1`"
-    update_var X11_KBD_VARIANT "`echo "${newkbd}" | cut -d. -f2`"
+    update_var X11_KBD_LAYOUT  "${newkbd%.*}"
+    update_var X11_KBD_VARIANT "${newkbd#*.}"
 fi
