Better logging in cables communication.

diff --git a/src/usr/local/libexec/cable/comm b/src/usr/local/libexec/cable/comm
--- a/src/usr/local/libexec/cable/comm
+++ b/src/usr/local/libexec/cable/comm
@@ -23,7 +23,7 @@ msgid="$2"
 
 
 error() {
-    echo "comm: $1" 1>&2
+    echo "comm (${msgid}): $1" 1>&2
     exit 1
 }
 
@@ -104,7 +104,7 @@ ack)
         rm -f "${pubqueue}"/"${msgid}"
 
         ackhash=`cat ${queue}/"${msgid}"/receipt.ack | tr -cd '[:xdigit:]' | tr A-F a-f`
-        [ ${#ackhash} = 128 ] || error "bad ackhash"
+        [ ${#ackhash} = 128 ] || error "bad ackhash in receipt.ack"
 
         curl -sSfg -o ${queue}/"${msgid}"/${cmd}.ans "${prefix}"/ack/"${msgid}"/"${ackhash}"
 
@@ -117,7 +117,7 @@ ack)
         rm -f "${pubqueue}"/"${msgid}"
         rm -r --one-file-system ${queue}/"${msgid}".del
     else
-        error "${cmd}.ok or ${msgid}.del not found"
+        error "${cmd}.ok or .del directory not found"
     fi
     ;;
 
@@ -127,7 +127,7 @@ fin)
         rm -f "${pubrqueue}"/"${msgid}"
         rm -r --one-file-system ${rqueue}/"${msgid}".del
     else
-        error "${msgid}.del not found"
+        error ".del directory not found"
     fi
     ;;
 
diff --git a/src/usr/local/libexec/cable/loop b/src/usr/local/libexec/cable/loop
--- a/src/usr/local/libexec/cable/loop
+++ b/src/usr/local/libexec/cable/loop
@@ -33,9 +33,13 @@ msgdir=${HOME}/persist/cables/${qtype}/"${msgid}"
 
 
 error() {
-    echo "loop: $1" 1>&2
+    echo "loop (${msgid}): $1" 1>&2
     exit 1
 }
+
+
+# Sanity checks
+[ ${#msgid} = 40 ] || error "bad msgid"
 
 
 # .del actions: blocking lock (to let the renaming action finish)
@@ -45,7 +49,7 @@ if [ "${dirid}" != "${msgid}" ]; then
         if [ -e "${msgdir}".del ]; then
             exec flock -w ${locktmout} "${msgdir}".del/ "${comm}" ack "${msgid}"
         else
-            error "${msgid}.del not found"
+            error ".del directory not found"
         fi
 
     else
@@ -53,7 +57,7 @@ if [ "${dirid}" != "${msgid}" ]; then
         if [ -e "${msgdir}".del ]; then
             exec flock -w ${locktmout} "${msgdir}".del/ "${comm}" fin "${msgid}"
         else
-            error "${msgid}.del not found"
+            error ".del directory not found"
         fi
 
     fi
@@ -80,7 +84,7 @@ else
                 "${comm}" send "${msgid}"
             fi
         else
-            error "${msgid}/send.req/rdy/ok not found"
+            error "send.req/rdy/ok not found"
         fi
 
         if   [ -e "${msgdir}"/ack.rdy ]; then
@@ -114,7 +118,7 @@ else
         elif [ -e "${msgdir}"/recv.ok  ]; then
             exec "${comm}"   recv "${msgid}"
         else
-            error "${msgid}/recv.req/rdy/ok not found"
+            error "recv.req/rdy/ok not found"
         fi
 
     fi
diff --git a/src/usr/local/libexec/cable/mhdrop b/src/usr/local/libexec/cable/mhdrop
--- a/src/usr/local/libexec/cable/mhdrop
+++ b/src/usr/local/libexec/cable/mhdrop
@@ -29,7 +29,7 @@ fi
 
 
 error() {
-    echo "mhdrop: $1" 1>&2
+    echo "mhdrop (${msg}): $1" 1>&2
     exit 1
 }
 
@@ -46,7 +46,7 @@ getfreemsg() {
     last=$((last + 1))
 
     if [ -e ${inbox}/${last} ]; then
-        error "failed to create new message name"
+        error "failed to create unique message name"
     fi
 
     echo ${last}
@@ -58,5 +58,5 @@ mv -nT -- "${msg}" ${inbox}/"${freemsg}"
 
 
 if [ -e "${msg}" ]; then
-    error "failed to move ${msg} to inbox"
+    error "failed to move message to inbox"
 fi
