Build-time updates, pending a fresh build test
Removed packages:
  gconf-editor and all GConf configuration files
  Totem, gedit, AbiWord, VIPS / nip2, IsoMaster
  emelFM2, Pidgin, gFTP, uGet, eBoard, GNUChess
  Xmahjongg, parcellite, florence, File-Roller
  e3, Geeqie, ufraw, Qalculate, mkspeech script,
  Ghostscript, fbida, Gnumeric, DjVu
Removed corresponding user configuration files.
Changed lxpolkit to polkit-gnome.
Enabled predictable network interface names.
Added /dev/shm to chroot mounts.
Upgraded kernel to 3.14.5.
Removed non-64-bit KEXEC kernel.
Updated compilation flags to prepare for 64-bit migration.
Enabled SSE2 and SSE3 USE-flags.
Disabled GRKERNSEC_KMEM due to need of KEXEC.
Enabled GRKERNSEC_RANDSTRUCT.
Enabled PROC_FS in KEXEC (#517182).
Added open-vm-tools-kmod UID/GID patch (#507026).
Updated VirtualBox patches (#424816).
Updated firmware files.
Removed main user from "lp" group (unnecessary for net-wireless/bluez).

Closes (GitHub: #12, #13, #14, #17).

diff --git a/src/root/patches/portage/virtualbox-guest-additions.patch b/src/root/patches/portage/virtualbox-guest-additions.patch
--- a/src/root/patches/portage/virtualbox-guest-additions.patch
+++ b/src/root/patches/portage/virtualbox-guest-additions.patch
@@ -1,29 +1,10 @@
---- /usr/portage/app-emulation/virtualbox-guest-additions/virtualbox-guest-additions-4.2.18.ebuild	2013-06-24 10:58:49.000000000 +0000
-+++ /usr/portage/app-emulation/virtualbox-guest-additions/virtualbox-guest-additions-4.2.18.ebuild	2013-08-11 03:33:14.113055078 +0000
-@@ -49,7 +49,7 @@
- 
- pkg_setup() {
- 		linux-mod_pkg_setup
--		BUILD_PARAMS="KERN_DIR=${KV_DIR} KERNOUT=${KV_OUT_DIR}"
-+		BUILD_PARAMS="KERN_DIR=${KV_OUT_DIR} KERNOUT=${KV_OUT_DIR}"
- 		enewgroup vboxguest
- 		enewuser vboxguest -1 /bin/sh /dev/null vboxguest
- }
-@@ -83,6 +83,9 @@
- 				"${WORKDIR}/${mdir}/${vboxheader}"
- 		done
- 	done
-+
-+	# Fix split kernels includes
-+	sed -i 's@\<kernelpath\>\(.*/generated\>\)@VBOX_LINUX_SRC\1@' "${S}"/Config.kmk
- }
- 
- src_configure() {
-@@ -92,6 +95,7 @@
- 		--disable-sdl-ttf \
- 		--disable-pulse \
- 		--disable-alsa \
-+		--with-linux=${KV_OUT_DIR} \
- 		--build-headless || die "configure failed"
+--- /usr/portage/app-emulation/virtualbox-guest-additions/virtualbox-guest-additions-4.3.10.ebuild	2014-07-15 20:43:25.482992744 +0000
++++ /usr/portage/app-emulation/virtualbox-guest-additions/virtualbox-guest-additions-4.3.10.ebuild	2014-07-15 20:43:43.226748144 +0000
+@@ -95,6 +95,7 @@
+ 	--disable-sdl-ttf \
+ 	--disable-pulse \
+ 	--disable-alsa \
++	--with-linux=${KV_OUT_DIR} \
+ 	--build-headless || die "configure failed"
  }
  
